version: '3.8'
services:
  iouone_db:
    build:
      context: ./iouone-db
    image: fallsoft/iouone_db:latest
    ports:
      - 3306:3306
    container_name: iouone_db
    environment:
      - MYSQL_ROOT_PASSWORD=IouOne@147
      - MYSQL_USER=iouone
      - MYSQL_PASSWORD=iouone-db
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  iouone-serv:
    build:
      context: ../iouone-serv
      dockerfile: ../iouone-serv/Dockerfile
      args:
        EXPOSE_PORT: 7071
    image: fallsoft/iouone-serv:latest
    ports:
      - 7071:7071
    container_name: iouone-serv
    environment:
      spring.profiles.active: prd
      SPRING_DATASOURCE_URL: jdbc:mysql://srv654370.hstgr.cloud:3306/iouone_prd?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: iouone
      SPRING_DATASOURCE_PASSWORD: iouone-db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - iouone_db
    networks:
      - backend
    restart: unless-stopped
networks:
  backend:
    name: backend
    driver: "bridge"