spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/iouone?useTimezone=true&serverTimezone=UTC
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
jwt:
  public:
    key: classpath:public.pem
  private:
    key: classpath:private.pem