spring:
  application:
    name: mspessoa
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:iouone}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/iouone_hml?useTimezone=true&serverTimezone=UTC}
    password: ${SPRING_DATASOURCE_PASSWORD:iouone-db}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
jwt:
  public:
    key: classpath:public.pem
  private:
    key: classpath:private.pem

server:
  port: ${PORT:7074}
springdoc:
  swagger-ui:
    enabled: true
    urls:
      - url: /v3/api-docs
        name: IOUONE API
    server-url: http://plataforma-hml.iouone.com.br

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

mq:
  queue:
    pessoa_registration: pessoa_registration_queue
    receiving_customer: receiving_customer_id_queue