spring:
  application:
    name: mspessoa
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/iouone?useTimezone=true&serverTimezone=UTC
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

jwt:
  public:
    key: classpath:public.pem
  private:
    key: classpath:private.pem

server:
  port: 7071
springdoc:
  swagger-ui:
    enabled: true
    urls:
      - url: /v3/api-docs
        name: IOUONE API
    server-url: http://localhost:${local.server.port}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mq:
  queue:
    pessoa_registration: pessoa_registration_queue
    receiving_customer: receiving_customer_id_queue

urls:
  apis:
    pagamento: http://localhost:7072

